// export enum Role {
//     USER_ADMIN = 'user_admin',
//     CABANG = 'cabang',
//     AOSM = 'area_segmen',
//     AS_OFFICER = 'area_segmen_officer',
//     AS_MANAGER = 'area_segmen_manager',
//     RBC_ABCS = 'rbc_abcs_area',
//     RBC_OFFICER = 'rbc_officer',
//     RBC_BBC = 'rbc_bbc_staff',
//     AREA_MANAGER = 'area_manager',
//     OP_DEP = 'operational_deputy',
//     RBC_MANAGER = 'rbc_manager',
//     RCEOH = 'rceo_head',
//     DEP_HEAD = 'departement_head',
//     DCOR_TL = 'dcor_tl',
//     DCOR_HEAD = 'dcor_head',
//     GROUP_HEAD = 'group_head',
//     MANAJEMEN = 'manajemen',
//     UIC = 'uic',
//     SOR_HEAD = 'sor_head',
//     USER_ALL = 'user_all',
//     USER = 'user',
//     UNASSIGNED = 'unassigned',
//   }
export enum Role {
  USER_ADMIN = 'user_admin',
  RISK_ADMIN = 'risk_admin',
  DEPT_HEAD = 'dept_head',
  DCOR = 'dcor',
  GROUP_HEAD = 'group_head',
  SORH = "sorh",
  SUPER_USER = 'super_user',
  SPV = 'spv',
  INPUTER = 'inputer',
  REVIEWER = 'reviewer',
  APPROVER = 'approver',
  ADMIN_MAKER = 'admin_maker',
  ADMIN_APPROVE = 'admin_approve',
  PEMBUKU_APPROVE = 'pembukuApprove',
}
